title: AI Productivity Blog
description: AI tools, automation strategies, and productivity hacks.

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Base Settings
show_excerpts: true
minimal_mistakes_skin: "default"  # Options: "default", "air", "aqua", "contrast", "dark", etc.

# Navigation Bar
nav:
  - title: "Home"
    url: /
  - title: "AI Tools"
    url: /ai-tools/
  - title: "Automation Guides"
    url: /automation-guides/
  - title: "Side Hustles"
    url: /side-hustles/
  - title: "About"
    url: /about/

# Sidebar
sidebar:
  - name: "AI Productivity Blog"
    image: "/assets/images/logo.png"
    about: "Your go-to resource for AI tools and automation strategies."
    social:
      - title: "Twitter"
        url: "https://twitter.com/yourhandle"
      - title: "LinkedIn"
        url: "https://linkedin.com/in/yourprofile"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

