title: "AI Productivity Blog"
description: "Exploring AI tools, automation strategies, and productivity hacks."
baseurl: "/ai-productivity-blog"
url: "https://peterb45.github.io"

# Minima theme settings
theme: minima

# Minima-specific settings
minima:
  skin: auto
  social_links: []
  date_format: "%b %-d, %Y"

# Navigation settings
header_pages:
  - index.md

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown Processing
markdown: kramdown
