theme: minima
title: AI Productivity Blog
description: AI tools, automation strategies, and productivity hacks to help individuals and businesses work smarter.

# Prevents Jekyll from automatically displaying the title again
show_title: false

# Navigation links for header
header_pages:
  - Best_AI_Productivity_Tools_in_2025.md
  - How_to_Automate_Your_Business_with_AI.md

# Set the base URL (Optional: Remove if not using a custom domain)
# baseurl: "/ai-productivity-blog"

# GitHub Pages settings (Optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
