# Site settings
title: AI Productivity Blog
description: AI tools, automation strategies, and productivity hacks to help individuals and businesses work smarter.
theme: minima

# Minima-specific settings
minima:
  skin: auto
  social_links: []

# Prevent duplicate titles
show_title: false  

# Navigation links for header
header_pages:
  - Best_AI_Productivity_Tools_in_2025.md
  - How_to_Automate_Your_Business_with_AI.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Base URL settings (Ensure it's correct)
baseurl: "/ai-productivity-blog"  # Repository name
url: "https://peterb45.github.io"  # GitHub Pages base domain

# Markdown settings
markdown: kramdown
