title: AI Productivity Blog
description: AI tools, automation strategies, and productivity hacks to help individuals and businesses work smarter.
theme: minima

# Minima-specific settings
show_excerpts: true  # Show summaries instead of full posts on the homepage
show_title: false  # Prevents duplicate titles

# Navigation links for header
header_pages:
  - Best_AI_Productivity_Tools_in_2025.md
  - How_to_Automate_Your_Business_with_AI.md

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima settings
minima:
  skin: auto
  social_links: []

# Base URL (Ensure it's correct)
baseurl: "/ai-productivity-blog"
url: "https://peterb45.github.io"

# Markdown processing
markdown: kramdown
